# Generated by Django 5.1 on 2024-09-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_category_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
